name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🧰 Enhancements'
    labels:
      - 'enhancement'
      - 'chore'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
exclude-labels:
  - dependencies
  - docs
  - testing
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  > Come talk to us directly on our [Discord channel](http://bit.ly/guild-chat)
  > Contact us here: [the-guild.dev](https://the-guild.dev/)

  ## What’s Changed

  $CHANGES
